---
-   id: poetry
    name: poetry
    entry: poetry
    language: python
    args: []
    require_serial: true
    pass_filenames: false
    additional_dependencies: []
    minimum_pre_commit_version: 0.14.0
